USED_CONFIG: DevelopmentConfig


DefaultConfig:
  App:
    NAME: test
  Flask:
    # http://flask.pocoo.org/docs/0.10/config/
    DEBUG: False
    TESTING: False


ProductionConfig:
  Base: DefaultConfig


DevelopmentConfig:
  Base: DefaultConfig

  Flask:
    DEBUG: True


TestingConfig:
  Base: DefaultConfig

  Flask:
    TESTING: True
